### ISSUE TITLE
Enable registering multiple instances of lifecycle tracking

### ISSUE THREAD

**Issue by southwood** [Microsoft/ApplicationInsights-Android#42]
we would keep the default instance and default registration but enable users to register a second instance with a separate telemetry client

**Comment by JoshuaWeber** [comment]
I'm not sure I understand the scenario behind this. Is this so I can have 2 telemetry clients? With possibly different iKeys / config. And both would be able to track lifecycle sessions?

**Comment by ElektrojungeAtWork** [comment]
Moving this to the backlog, will be part of future refactorings.

**Comment by ElektrojungeAtWork** [comment]
Closing this as we won't do this.
