### ISSUE TITLE
Memory leak in com.microsoft.commonlogging.channel.Persistence.ctx

### ISSUE THREAD

**Issue by caltseng** [Microsoft/ApplicationInsights-Android#66]
I'm using LeakCanary to look for memory leaks, and it looks like there is a static instance of Context being kept in Persistence. 

08-06 15:22:09.320   8729-16627/D/LeakCanary﹕ \* GC ROOT static com.microsoft.commonlogging.channel.Persistence.ctx

If you have more questions or want the full logs, I am a Microsoft employee. You can email me at calebt@microsoft.com.

**Comment by ElektrojungeAtWork** [comment]
Closing this as the CLL team supposedly fixed the issue.
