### ISSUE TITLE
NullPointerException when calling trackMetric with a null properties map

### ISSUE THREAD

**Issue by artsterb** [Microsoft/ApplicationInsights-Android#78]
Steps:
1) Call TrackMetric with a null properties map

Result:
In the logCat output you will see the following exception that is eaten by the sdk, which is probably ok given that I don't want properties checked anyway and it doesn't cause my app to crash, it is just noise.

Expected:
No exception.

The code here should add a check if properties is null before call HashMap new on it:
    protected TrackDataOperation(TrackDataOperation$DataType type, String metricName, double metric, Map<String, String> properties) {
        this.a = type;
        this.h = metric;

```
    try {
        this.b = (String)this.a(metricName);
        this.c = new HashMap(properties);
    } catch (Exception var7) {
        var7.printStackTrace();
    }
}
```

Here's the useful part of the stack:
01-25 10:06:54.790 2387-2387/com.hockeyapp.hockeydevapp W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.Map.size()' on a null object reference
01-25 10:06:54.793 2387-2387/com.hockeyapp.hockeydevapp W/System.err:     at java.util.HashMap.<init>(HashMap.java:195)
01-25 10:06:54.793 2387-2387/com.hockeyapp.hockeydevapp W/System.err:     at com.microsoft.applicationinsights.library.TrackDataOperation.<init>(TrackDataOperation.java:81)
01-25 10:06:54.793 2387-2387/com.hockeyapp.hockeydevapp W/System.err:     at com.microsoft.applicationinsights.library.TelemetryClient.trackMetric(TelemetryClient.java:242)
01-25 10:06:54.793 2387-2387/com.hockeyapp.hockeydevapp W/System.err:     at com.microsoft.applicationinsights.library.TelemetryClient.trackMetric(TelemetryClient.java:229)
01-25 10:06:54.793 2387-2387/com.hockeyapp.hockeydevapp W/System.err:     at com.hockeyapp.hockeydevapp.helper.TelemetryWrapper.trackMetric(TelemetryWrapper.java:26)

**Comment by ElektrojungeAtWork** [comment]
Fixed in latest release
