### ISSUE TITLE
trackHandledException not defined - 1.0-beta.9

### ISSUE THREAD

**Issue by Hashemalrifai** [Microsoft/ApplicationInsights-Android#79]
Hi, this is my first time using ApplicationInsights in Android, but I can't track exceptions. 
I can see trackEvent, trackTrace... but not trackHandledException. 
I looked also at the source code and didn't find that method. Is that new in this version or what?
I'm using version 1.0-beta.9 and Android Studio
Thanks..

**Comment by matthiaswenz** [comment]
Hi @Hashemalrifai,
as stated in our [change log](https://github.com/Microsoft/ApplicationInsights-Android/blob/master/CHANGELOG.md#10-beta9) `trackHandledException` was removed from the feature set of the SDK for 1.0-beta.9.

**Comment by ElektrojungeAtWork** [comment]
Closing this as it was intentionally removed from the SDK.
