### ISSUE TITLE
Mark application insights as "deprecated"

### ISSUE THREAD

**Issue by jaredsburrows** [Microsoft/ApplicationInsights-Android#85]
Can we publish a v1.0 release of application insights?

**Comment by matthiaswenz** [comment]
Hi @jaredsburrows - we have decided that HockeyApp is our major offering for mobile and cross-plattform crash reporting, beta distribution and user feedback, this means there is no active support on the Application Insights mobile SDKs going on.
Thus we will not release a stable version of the SDK.

Best,
Mat

**Comment by jaredsburrows** [comment]
@ranterle Thanks for the fast response. Can you please add "Deprecated" to the description in the README and point to the HockeyApp repo?

**Comment by jaredsburrows** [comment]
Do you mind adding a link to the README.md to https://github.com/bitstadium/HockeySDK-Android?

**Comment by matthiaswenz** [comment]
In the readme under the section **Breaking Changes** both the deprecation and HockeyApp as the go-to alternative are mentioned.

**Comment by jaredsburrows** [comment]
@ranterle Awesome!
