### ISSUE TITLE
Multiple instances of the same event being reported 

### ISSUE THREAD

**Issue by jorgecoca** [Microsoft/ApplicationInsights-Android#86]
I'm using `com.microsoft.azure:applicationinsights-android:1.0-beta.10` in my Android app, and I've noticed that, in some occasions, it is reporting the same event multiple times; sometimes it is working fine, but some others it reports 2, 3 or 4 times the same event for the same user, and almost with an identical timestamp. 

I haven't been able to find the root cause, or even how to reproduce it.

Thanks,
Jorge

**Comment by ElektrojungeAtWork** [comment]
Hi @jorgecoca,
we're not aware of any issues but that said, the Application Insights SDK is officially deprecated. Please switch to [HockeyApp](https://hockeyapp.net) or consider to [MobileCenter](https://www.visualstudio.com/vs/mobile-center/).

You can find more about the transition from Application Insights to HockeyApp [here](https://www.hockeyapp.net/blog/2016/03/11/welcome-application-insights-users.html) and about how Mobile Center will be the future of HockeyApp [here](https://www.hockeyapp.net/blog/2016/11/16/mobile-center-next-generation-hockeyapp.html).

Please don't hesitate to get in touch.

Best,
Benny
