### ISSUE TITLE
How to log exceptions?

### ISSUE THREAD

**Issue by xperiandri** [Microsoft/ApplicationInsights-Android#87]
What is the problem to implement automatic unhandled exception logging?

**Comment by ElektrojungeAtWork** [comment]
Hey @xperiandri,

Thank you for getting in touch. Crash Reporting was removed from the SDK in version 1.0-beta.9 and won't come back as the SDK is officially deprecated. Please switch to [HockeyApp](https://hockeyapp.net) or consider switching to [MobileCenter](https://www.visualstudio.com/vs/mobile-center/).

You can find more about the transition from Application Insights to HockeyApp [here](https://www.hockeyapp.net/blog/2016/03/11/welcome-application-insights-users.html) and about how Mobile Center will be the future of HockeyApp [here](https://www.hockeyapp.net/blog/2016/11/16/mobile-center-next-generation-hockeyapp.html).

Please don't hesitate to get in touch.

Best,
Benny
